---
title: "Process data files from prosodylab-jspsych-helper"
output:
  html_document:
    df_print: paged
---

This notebook illustrates how to process data collected with the prosodylab-jspsych-helper.  

The different steps These should eventually be turned into functions defined in separate R scripts.

```{r}
require(jsonlite)
require(tidyverse)
library(httr)
library(ggplot2)
library(tidyverse)
library(lme4)
library(languageR)
library(reshape)
library(scales)
library(texreg)
library(car)
library(grid)
library(gridExtra)
library(xtable)
library(brms)
library(cowplot)

pathStudy = '/Users/chael/Dropbox/experimenter/reho/experiment'
setwd(pathStudy)
source("prosodylabRhelper.R")

```


```{r}
# Process data

studyFileName = 'reho.txt'

d = importData(paste0(pathStudy,'/data'),paste0(pathStudy,'/',studyFileName))

n_distinct(d$participant)

d = filter(d,trialPart=='plannedProduction')

acoustics = read.csv(paste0(pathStudy,'/data/recordedFilesAcoustics/pritl_acoustics.txt'), sep='\t') 

d = merge(acoustics,d,
          all.x=TRUE,
          by=c("experiment","item","condition","participant"),
          suffixes=c("",".other")
          )

d$Stress=NA
d$Stress='FinalStress'
d$Stress[d$condition=='1']='InitialStress'
d$Stress[d$Syllables=='3syl'&d$condition=='2']='MedialStress'
d$Stress=factor(d$Stress,levels=c('InitialStress','MedialStress','FinalStress'))
summary(d$Stress)

d$Word = "SecondWord"
d$Word[d$woiLabel<3]="FirstWord"
d$Word[d$woiLabel==3&d$Syllables=='3syl']="FirstWord"
d$Word[d$woiLabel>4&d$Syllables=='2syl']="ThirdWord"
d$Word=factor(d$Word)
summary(d$Word)


d$SyllablePosition='FinalSyllable'
d$SyllablePosition[d$Syllables=='2syl'&d$woiLabel%in%c('1','3','5')]='InitialSyllable'
d$SyllablePosition[d$Syllables=='3syl'&d$woiLabel%in%c('1','4')]='InitialSyllable'
d$SyllablePosition[d$Syllables=='3syl'&d$woiLabel%in%c('2','5')]='MedialSyllable'
d$SyllablePosition=factor(d$SyllablePosition,levels=c('InitialSyllable','MedialSyllable','FinalSyllable'))
summary(d$SyllablePosition)

d$WordPosition=ordered(d$Word)


d %>% group_by(participant) %>%
  dplyr::summarise (n = n(), meanGroup=mean(grouping,na.rm=T),meanHeadphone=mean(headPhoneScreenerScore))  %>%
  as.data.frame

d %>% group_by(participant) %>%
  summarise(unique(DebriefingIssues)) %>%
  as.data.frame


# exclude test participants 
#d = d %>% filter(!(participant %in% c('{{%SESSION_ID%}}','12345')))
# exclude participants who always or almost always  clicked same button
#d = d %>% filter(!(participant %in% c('5ec3438ac7c19900086a40f9')))
# exclude participants who failed headPhoneScreener?
#d = d %>% filter(headPhoneScreenerScore >  0.75)


n_distinct(d$participant)

```


## Grouping and Prominence Response


### Two syllable word

```{r}


intensity.plot = ggplot(filter(d,maxIntensity>50&Syllables=='2syl'), 
                        aes(x=SyllablePosition, y=maxIntensity)) +  
  geom_boxplot()  + 
  geom_jitter(alpha=0.1) +
  xlab('') + 
  ylab('Intensity (dB)') +
  theme_bw(base_size = figureFontSize)  +
  facet_grid(Word~Stress, scales = "fixed") +
  ggtitle('Intensity') +
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

duration.plot = ggplot(filter(d,maxIntensity>50&Syllables=='2syl'), 
                       aes(x=SyllablePosition, y=duration)) +  
  geom_boxplot()  + 
  geom_jitter(alpha=0.1) +
  xlab('') +
  ylab('Duration (sec on log scale)') +
  coord_trans(y = "log10") +
  theme_bw(base_size =  figureFontSize) +
  facet_grid(Word~Stress, scales = "fixed") +
  ggtitle('Duration') +
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
#

grid.arrange(intensity.plot,duration.plot, ncol = 1, nrow = 2)

```



